[package]
name = "todo_back_end"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = "0.75.0"
serde = "1.0.217"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
