name = "UiRoot"
id = "app_router"
# History, Switch, History是历史模式，记录页面历史，当使用nav_back()时会一直返回直到没有历史记录
# Switch是切换模式，不记录历史，当使用nav_back()时会直接返回到上一个页面，呈现出两个页面之间的切换效果
mode = "History"
active = "login" # 默认显示的页面


# 配置tabbar，tabbar会和bar_pages中的配置一一对应
[tabbar]
theme = "Dark"
login = {icon = "crate://self/resources/login.svg", text = "Login Page"}
register = {icon = "crate://self/resources/register.svg", text = "Register Page"}
use = true # 是否使用tabbar

# 配置有两种方式, 一种是直接配置, 一种是通过配置文件引入
# 配置bar页面，bar页面是主要页面，当启用tabbar时，bar页面会显示在tabbar上
[bar_pages]
# 说明Login页面的路径为: crate::views::login, 组件为Login
login = { path = "crate::views::login::*", component = "Login" }
# 说明Register页面的路径为: crate::views::register, 组件为Register
register = "crate::views::register::Register"

# 配置nav页面，nav页面属于次要页面，并不会与tabbar有联系，常使用nav_to()进行跳转，并且nav页面具有header，提供快速返回
[nav_pages]
nav_home = { path = "crate::views::home::*", component = "Home" }
nav_todo = { path = "crate::views::todo::*", component = "Todo" }
nav_about = { path = "crate::views::about::*", component = "About" }
